### ISSUE TITLE
htaccess leads to Internal Server Error

### ISSUE THREAD

**Issue by BenjaminKlatt** [Schepp/CSS-JS-Booster#56]
Hi, 

using the .htaccess file in the booster directory as provided here, I get an Internal Server Error (500).
It is an Apache 2.4 with PHP 5.2.x

As soon as I comment the following lines, it does work properly:

```
    #Give access even if webmaster has globally forbidden access
    #Order deny,allow
    #Allow from all
    #Satisfy any
```

Are they really necessary as long as the script now works as expected?

thanks
Benjamin

**Comment by Schepp** [comment]
Not nessessary if it works for you. And hi! btw! :)
